<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class MedicineSeeder extends Seeder
{
    public function run()
    {
        $now = date('Y-m-d H:i:s');

        // Dates for inventory display (expiry dates must be > 3 months from today)
        $future1 = date('Y-m-d', strtotime('+8 months'));  // MED-001
        $future2 = date('Y-m-d', strtotime('+6 months')); // MED-002 (out of stock but valid expiry)
        $future3 = date('Y-m-d', strtotime('+12 months')); // MED-003
        $future4 = date('Y-m-d', strtotime('+10 months')); // MED-004
        $future5 = date('Y-m-d', strtotime('+9 months'));  // MED-005

        // Dates for expired/expiring items (for Stock Out section testing)
        $expired = date('Y-m-d', strtotime('-2 months'));
        $recentlyExpired = date('Y-m-d', strtotime('-10 days'));
        $today = date('Y-m-d');
        $nearFuture = date('Y-m-d', strtotime('+20 days')); // Within 3 months

        $medicines = [
            [
                'id' => 'MED-001',
                'barcode' => 'RX-1001',
                'name' => 'Amoxicillin 500mg Capsule',
                'brand' => 'PharmaCare',
                'category' => 'Antibiotic',
                'stock' => 150,
                'unit_price' => 4.50,
                'retail_price' => 7.99,
                'manufactured_date' => date('Y-m-d', strtotime('-6 months')),
                'expiry_date' => $future1,
                'description' => 'Broad-spectrum antibiotic for bacterial infections.',
                'created_at' => $now,
            ],
            [
                'id' => 'MED-002',
                'barcode' => 'RX-1002',
                'name' => 'Cetirizine 10mg Tablet',
                'brand' => 'AllerFree',
                'category' => 'Antihistamine',
                'stock' => 0, // Stock out scenario - will show in "Out of Stock" section
                'unit_price' => 2.10,
                'retail_price' => 3.75,
                'manufactured_date' => date('Y-m-d', strtotime('-4 months')),
                'expiry_date' => $future2, // Valid expiry but stock = 0
                'description' => 'Antihistamine for allergy relief. Currently out of stock.',
                'created_at' => $now,
            ],
            [
                'id' => 'MED-003',
                'barcode' => 'RX-1003',
                'name' => 'Ascorbic Acid 500mg Tablet',
                'brand' => 'VitaBoost',
                'category' => 'Vitamin',
                'stock' => 320,
                'unit_price' => 1.25,
                'retail_price' => 2.20,
                'manufactured_date' => date('Y-m-d', strtotime('-3 months')),
                'expiry_date' => $future3,
                'description' => 'Immune support supplement with vitamin C.',
                'created_at' => $now,
            ],
            [
                'id' => 'MED-004',
                'barcode' => 'RX-1004',
                'name' => 'Ibuprofen 400mg Tablet',
                'brand' => 'PainAway',
                'category' => 'Analgesic',
                'stock' => 85,
                'unit_price' => 1.85,
                'retail_price' => 3.00,
                'manufactured_date' => date('Y-m-d', strtotime('-9 months')),
                'expiry_date' => $future4,
                'description' => 'Pain reliever and anti-inflammatory medication.',
                'created_at' => $now,
            ],
            [
                'id' => 'MED-005',
                'barcode' => 'RX-1005',
                'name' => 'Oral Rehydration Salts',
                'brand' => 'HydraPlus',
                'category' => 'Electrolyte',
                'stock' => 40,
                'unit_price' => 0.95,
                'retail_price' => 1.80,
                'manufactured_date' => date('Y-m-d', strtotime('-2 months')),
                'expiry_date' => $future5,
                'description' => 'Oral rehydration salts for dehydration treatment.',
                'created_at' => $now,
            ],
            [
                'id' => 'MED-006',
                'barcode' => 'RX-1006',
                'name' => 'Paracetamol 500mg Tablet',
                'brand' => 'Biogesic',
                'category' => 'Analgesic',
                'stock' => 3, // Low stock
                'unit_price' => 1.50,
                'retail_price' => 2.50,
                'manufactured_date' => date('Y-m-d', strtotime('-1 month')),
                'expiry_date' => date('Y-m-d', strtotime('+7 months')),
                'description' => 'Pain reliever and fever reducer.',
                'created_at' => $now,
            ],
            [
                'id' => 'MED-007',
                'barcode' => 'RX-1007',
                'name' => 'Loratadine 10mg Tablet',
                'brand' => 'Loratin',
                'category' => 'Antihistamine',
                'stock' => 200,
                'unit_price' => 2.75,
                'retail_price' => 4.50,
                'manufactured_date' => date('Y-m-d', strtotime('-2 months')),
                'expiry_date' => date('Y-m-d', strtotime('+11 months')),
                'description' => 'Non-drowsy antihistamine for allergy relief.',
                'created_at' => $now,
            ],
            [
                'id' => 'MED-008',
                'barcode' => 'RX-1008',
                'name' => 'Metformin 500mg Tablet',
                'brand' => 'RiteMed',
                'category' => 'Antidiabetic',
                'stock' => 5, // Low stock
                'unit_price' => 3.25,
                'retail_price' => 5.00,
                'manufactured_date' => date('Y-m-d', strtotime('-5 months')),
                'expiry_date' => date('Y-m-d', strtotime('+6 months')),
                'description' => 'Antidiabetic medication for type 2 diabetes.',
                'created_at' => $now,
            ],
            [
                'id' => 'MED-009',
                'barcode' => 'RX-1009',
                'name' => 'Omeprazole 20mg Capsule',
                'brand' => 'GastriCare',
                'category' => 'Antacid',
                'stock' => 120,
                'unit_price' => 3.50,
                'retail_price' => 6.00,
                'manufactured_date' => date('Y-m-d', strtotime('-3 months')),
                'expiry_date' => date('Y-m-d', strtotime('+9 months')),
                'description' => 'Proton pump inhibitor for acid reflux and ulcers.',
                'created_at' => $now,
            ],
            [
                'id' => 'MED-010',
                'barcode' => 'RX-1010',
                'name' => 'Salbutamol 2mg Tablet',
                'brand' => 'AsthmaRelief',
                'category' => 'Bronchodilator',
                'stock' => 75,
                'unit_price' => 2.80,
                'retail_price' => 4.75,
                'manufactured_date' => date('Y-m-d', strtotime('-4 months')),
                'expiry_date' => date('Y-m-d', strtotime('+8 months')),
                'description' => 'Bronchodilator for asthma and COPD treatment.',
                'created_at' => $now,
            ],
            [
                'id' => 'MED-011',
                'barcode' => 'RX-1011',
                'name' => 'Amlodipine 5mg Tablet',
                'brand' => 'CardioMed',
                'category' => 'Antihypertensive',
                'stock' => 95,
                'unit_price' => 4.20,
                'retail_price' => 7.50,
                'manufactured_date' => date('Y-m-d', strtotime('-2 months')),
                'expiry_date' => date('Y-m-d', strtotime('+10 months')),
                'description' => 'Calcium channel blocker for hypertension.',
                'created_at' => $now,
            ],
            [
                'id' => 'MED-012',
                'barcode' => 'RX-1012',
                'name' => 'Losartan 50mg Tablet',
                'brand' => 'HypertensCare',
                'category' => 'Antihypertensive',
                'stock' => 110,
                'unit_price' => 5.00,
                'retail_price' => 8.50,
                'manufactured_date' => date('Y-m-d', strtotime('-5 months')),
                'expiry_date' => date('Y-m-d', strtotime('+7 months')),
                'description' => 'Angiotensin receptor blocker for blood pressure control.',
                'created_at' => $now,
            ],
            [
                'id' => 'MED-013',
                'barcode' => 'RX-1013',
                'name' => 'Atorvastatin 20mg Tablet',
                'brand' => 'CholestCare',
                'category' => 'Antilipemic',
                'stock' => 88,
                'unit_price' => 6.50,
                'retail_price' => 11.00,
                'manufactured_date' => date('Y-m-d', strtotime('-6 months')),
                'expiry_date' => date('Y-m-d', strtotime('+6 months')),
                'description' => 'Statin medication for cholesterol management.',
                'created_at' => $now,
            ],
            [
                'id' => 'MED-014',
                'barcode' => 'RX-1014',
                'name' => 'Levothyroxine 50mcg Tablet',
                'brand' => 'ThyroCare',
                'category' => 'Hormone',
                'stock' => 65,
                'unit_price' => 3.75,
                'retail_price' => 6.50,
                'manufactured_date' => date('Y-m-d', strtotime('-1 month')),
                'expiry_date' => date('Y-m-d', strtotime('+11 months')),
                'description' => 'Thyroid hormone replacement therapy.',
                'created_at' => $now,
            ],
            [
                'id' => 'MED-015',
                'barcode' => 'RX-1015',
                'name' => 'Ciprofloxacin 500mg Tablet',
                'brand' => 'BactriMed',
                'category' => 'Antibiotic',
                'stock' => 45,
                'unit_price' => 5.50,
                'retail_price' => 9.00,
                'manufactured_date' => date('Y-m-d', strtotime('-7 months')),
                'expiry_date' => date('Y-m-d', strtotime('+5 months')),
                'description' => 'Fluoroquinolone antibiotic for bacterial infections.',
                'created_at' => $now,
            ],
            [
                'id' => 'MED-016',
                'barcode' => 'RX-1016',
                'name' => 'Furosemide 40mg Tablet',
                'brand' => 'Diurex',
                'category' => 'Diuretic',
                'stock' => 70,
                'unit_price' => 2.25,
                'retail_price' => 4.00,
                'manufactured_date' => date('Y-m-d', strtotime('-3 months')),
                'expiry_date' => date('Y-m-d', strtotime('+9 months')),
                'description' => 'Loop diuretic for edema and hypertension.',
                'created_at' => $now,
            ],
            [
                'id' => 'MED-017',
                'barcode' => 'RX-1017',
                'name' => 'Warfarin 5mg Tablet',
                'brand' => 'BloodThin',
                'category' => 'Anticoagulant',
                'stock' => 55,
                'unit_price' => 4.80,
                'retail_price' => 8.25,
                'manufactured_date' => date('Y-m-d', strtotime('-4 months')),
                'expiry_date' => date('Y-m-d', strtotime('+8 months')),
                'description' => 'Anticoagulant for blood clot prevention.',
                'created_at' => $now,
            ],
            [
                'id' => 'MED-018',
                'barcode' => 'RX-1018',
                'name' => 'Montelukast 10mg Tablet',
                'brand' => 'AsthmaGuard',
                'category' => 'Antiasthmatic',
                'stock' => 90,
                'unit_price' => 7.25,
                'retail_price' => 12.50,
                'manufactured_date' => date('Y-m-d', strtotime('-2 months')),
                'expiry_date' => date('Y-m-d', strtotime('+10 months')),
                'description' => 'Leukotriene receptor antagonist for asthma control.',
                'created_at' => $now,
            ],
            [
                'id' => 'MED-019',
                'barcode' => 'RX-1019',
                'name' => 'Gliclazide 80mg Tablet',
                'brand' => 'DiabetCare',
                'category' => 'Antidiabetic',
                'stock' => 105,
                'unit_price' => 3.90,
                'retail_price' => 6.75,
                'manufactured_date' => date('Y-m-d', strtotime('-5 months')),
                'expiry_date' => date('Y-m-d', strtotime('+7 months')),
                'description' => 'Sulfonylurea for type 2 diabetes management.',
                'created_at' => $now,
            ],
            [
                'id' => 'MED-020',
                'barcode' => 'RX-1020',
                'name' => 'Diclofenac 50mg Tablet',
                'brand' => 'InflamCare',
                'category' => 'NSAID',
                'stock' => 130,
                'unit_price' => 2.50,
                'retail_price' => 4.25,
                'manufactured_date' => date('Y-m-d', strtotime('-1 month')),
                'expiry_date' => date('Y-m-d', strtotime('+11 months')),
                'description' => 'Nonsteroidal anti-inflammatory drug for pain and inflammation.',
                'created_at' => $now,
            ],
        ];

        $ids = array_column($medicines, 'id');
        if (! empty($ids)) {
            $this->db->table('medicines')->whereIn('id', $ids)->delete();
        }

        $this->db->table('medicines')->insertBatch($medicines);
    }
}
