<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class PatientSeeder extends Seeder
{
    public function run()
    {
        $now = date('Y-m-d H:i:s');
        
        // Get available bed IDs for inpatients (first 10 beds)
        $bedIds = $this->db->table('beds')
            ->select('id')
            ->where('status', 'Available')
            ->orderBy('id', 'ASC')
            ->limit(10)
            ->get()
            ->getResultArray();
        
        $availableBedIds = array_column($bedIds, 'id');
        $bedIndex = 0;

        $patients = [
            // INPATIENTS
            [
                'id' => 'PAT-241204-0001',
                'first_name' => 'Maria',
                'middle_name' => 'Santos',
                'last_name' => 'Cruz',
                'email' => 'maria.cruz@email.com',
                'phone' => '09171234567',
                'date_of_birth' => '1985-03-15',
                'gender' => 'female',
                'civil_status' => 'married',
                'place_of_birth' => 'Manila',
                'address' => '123 Rizal Street, Barangay Malate',
                'province' => 'Metro Manila',
                'city' => 'Manila',
                'barangay' => 'Malate',
                'street' => 'Rizal Street',
                'type' => 'inpatient',
                'bed_id' => isset($availableBedIds[$bedIndex]) ? $availableBedIds[$bedIndex++] : null,
                'blood_type' => 'O+',
                'emergency_contact_person' => 'Juan Cruz',
                'emergency_contact_relationship' => 'Husband',
                'emergency_contact_phone' => '09171234568',
                'insurance_provider' => 'PhilHealth',
                'insurance_number' => 'PH-123456789',
                'vitals_bp' => '120/80',
                'vitals_hr' => 72,
                'vitals_temp' => 36.5,
                'medical_history' => 'Hypertension, managed with medication',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'PAT-241204-0002',
                'first_name' => 'Juan',
                'middle_name' => 'Dela',
                'last_name' => 'Rosa',
                'email' => 'juan.rosa@email.com',
                'phone' => '09182345678',
                'date_of_birth' => '1978-07-22',
                'gender' => 'male',
                'civil_status' => 'single',
                'place_of_birth' => 'Quezon City',
                'address' => '456 EDSA, Barangay Kamuning',
                'province' => 'Metro Manila',
                'city' => 'Quezon City',
                'barangay' => 'Kamuning',
                'street' => 'EDSA',
                'type' => 'inpatient',
                'bed_id' => isset($availableBedIds[$bedIndex]) ? $availableBedIds[$bedIndex++] : null,
                'blood_type' => 'A+',
                'emergency_contact_person' => 'Maria Rosa',
                'emergency_contact_relationship' => 'Sister',
                'emergency_contact_phone' => '09182345679',
                'insurance_provider' => 'Maxicare',
                'insurance_number' => 'MAX-987654321',
                'vitals_bp' => '130/85',
                'vitals_hr' => 78,
                'vitals_temp' => 37.2,
                'medical_history' => 'Diabetes Type 2, post-surgical recovery',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'PAT-241204-0003',
                'first_name' => 'Ana',
                'middle_name' => 'Garcia',
                'last_name' => 'Lopez',
                'email' => 'ana.lopez@email.com',
                'phone' => '09193456789',
                'date_of_birth' => '1992-11-08',
                'gender' => 'female',
                'civil_status' => 'married',
                'place_of_birth' => 'Makati',
                'address' => '789 Ayala Avenue, Barangay Bel-Air',
                'province' => 'Metro Manila',
                'city' => 'Makati',
                'barangay' => 'Bel-Air',
                'street' => 'Ayala Avenue',
                'type' => 'inpatient',
                'bed_id' => isset($availableBedIds[$bedIndex]) ? $availableBedIds[$bedIndex++] : null,
                'blood_type' => 'B+',
                'emergency_contact_person' => 'Carlos Lopez',
                'emergency_contact_relationship' => 'Husband',
                'emergency_contact_phone' => '09193456790',
                'insurance_provider' => 'Cigna',
                'insurance_number' => 'CIG-456789123',
                'vitals_bp' => '110/70',
                'vitals_hr' => 65,
                'vitals_temp' => 36.8,
                'medical_history' => 'Postpartum care, normal delivery',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'PAT-241204-0004',
                'first_name' => 'Roberto',
                'middle_name' => 'Villanueva',
                'last_name' => 'Torres',
                'email' => 'roberto.torres@email.com',
                'phone' => '09204567890',
                'date_of_birth' => '1965-05-30',
                'gender' => 'male',
                'civil_status' => 'married',
                'place_of_birth' => 'Pasig',
                'address' => '321 Ortigas Avenue, Barangay San Antonio',
                'province' => 'Metro Manila',
                'city' => 'Pasig',
                'barangay' => 'San Antonio',
                'street' => 'Ortigas Avenue',
                'type' => 'inpatient',
                'bed_id' => isset($availableBedIds[$bedIndex]) ? $availableBedIds[$bedIndex++] : null,
                'blood_type' => 'AB+',
                'emergency_contact_person' => 'Carmen Torres',
                'emergency_contact_relationship' => 'Wife',
                'emergency_contact_phone' => '09204567891',
                'insurance_provider' => 'PhilHealth',
                'insurance_number' => 'PH-789123456',
                'vitals_bp' => '140/90',
                'vitals_hr' => 82,
                'vitals_temp' => 37.5,
                'medical_history' => 'Cardiac monitoring, chest pain evaluation',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'PAT-241204-0005',
                'first_name' => 'Liza',
                'middle_name' => 'Fernandez',
                'last_name' => 'Ramos',
                'email' => 'liza.ramos@email.com',
                'phone' => '09215678901',
                'date_of_birth' => '1988-09-12',
                'gender' => 'female',
                'civil_status' => 'single',
                'place_of_birth' => 'Taguig',
                'address' => '654 BGC High Street, Barangay Fort Bonifacio',
                'province' => 'Metro Manila',
                'city' => 'Taguig',
                'barangay' => 'Fort Bonifacio',
                'street' => 'BGC High Street',
                'type' => 'inpatient',
                'bed_id' => isset($availableBedIds[$bedIndex]) ? $availableBedIds[$bedIndex++] : null,
                'blood_type' => 'O-',
                'emergency_contact_person' => 'Pedro Ramos',
                'emergency_contact_relationship' => 'Father',
                'emergency_contact_phone' => '09215678902',
                'insurance_provider' => 'Medicard',
                'insurance_number' => 'MED-321654987',
                'vitals_bp' => '115/75',
                'vitals_hr' => 70,
                'vitals_temp' => 36.9,
                'medical_history' => 'Appendectomy recovery',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // OUTPATIENTS
            [
                'id' => 'PAT-241204-0006',
                'first_name' => 'Michael',
                'middle_name' => 'Tan',
                'last_name' => 'Lim',
                'email' => 'michael.lim@email.com',
                'phone' => '09226789012',
                'date_of_birth' => '1995-01-25',
                'gender' => 'male',
                'civil_status' => 'single',
                'place_of_birth' => 'Mandaluyong',
                'address' => '987 Shaw Boulevard, Barangay Wack-Wack',
                'province' => 'Metro Manila',
                'city' => 'Mandaluyong',
                'barangay' => 'Wack-Wack',
                'street' => 'Shaw Boulevard',
                'type' => 'outpatient',
                'bed_id' => null,
                'blood_type' => 'A-',
                'emergency_contact_person' => 'Jennifer Lim',
                'emergency_contact_relationship' => 'Sister',
                'emergency_contact_phone' => '09226789013',
                'insurance_provider' => 'Maxicare',
                'insurance_number' => 'MAX-147258369',
                'vitals_bp' => '125/80',
                'vitals_hr' => 75,
                'vitals_temp' => 37.0,
                'medical_history' => 'Regular check-up, no known allergies',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'PAT-241204-0007',
                'first_name' => 'Sarah',
                'middle_name' => 'Chua',
                'last_name' => 'Ng',
                'email' => 'sarah.ng@email.com',
                'phone' => '09237890123',
                'date_of_birth' => '1990-06-18',
                'gender' => 'female',
                'civil_status' => 'married',
                'place_of_birth' => 'Pasay',
                'address' => '147 Roxas Boulevard, Barangay Malibay',
                'province' => 'Metro Manila',
                'city' => 'Pasay',
                'barangay' => 'Malibay',
                'street' => 'Roxas Boulevard',
                'type' => 'outpatient',
                'bed_id' => null,
                'blood_type' => 'B-',
                'emergency_contact_person' => 'David Ng',
                'emergency_contact_relationship' => 'Husband',
                'emergency_contact_phone' => '09237890124',
                'insurance_provider' => 'Cigna',
                'insurance_number' => 'CIG-258369147',
                'vitals_bp' => '118/78',
                'vitals_hr' => 68,
                'vitals_temp' => 36.7,
                'medical_history' => 'Prenatal care, 24 weeks pregnant',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'PAT-241204-0008',
                'first_name' => 'James',
                'middle_name' => 'Reyes',
                'last_name' => 'Mendoza',
                'email' => 'james.mendoza@email.com',
                'phone' => '09248901234',
                'date_of_birth' => '1982-12-03',
                'gender' => 'male',
                'civil_status' => 'married',
                'place_of_birth' => 'Caloocan',
                'address' => '258 Rizal Avenue, Barangay Grace Park',
                'province' => 'Metro Manila',
                'city' => 'Caloocan',
                'barangay' => 'Grace Park',
                'street' => 'Rizal Avenue',
                'type' => 'outpatient',
                'bed_id' => null,
                'blood_type' => 'O+',
                'emergency_contact_person' => 'Grace Mendoza',
                'emergency_contact_relationship' => 'Wife',
                'emergency_contact_phone' => '09248901235',
                'insurance_provider' => 'PhilHealth',
                'insurance_number' => 'PH-369147258',
                'vitals_bp' => '135/88',
                'vitals_hr' => 80,
                'vitals_temp' => 37.1,
                'medical_history' => 'Hypertension follow-up, medication adjustment',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'PAT-241204-0009',
                'first_name' => 'Catherine',
                'middle_name' => 'Bautista',
                'last_name' => 'Aquino',
                'email' => 'catherine.aquino@email.com',
                'phone' => '09259012345',
                'date_of_birth' => '1993-04-20',
                'gender' => 'female',
                'civil_status' => 'single',
                'place_of_birth' => 'Marikina',
                'address' => '369 Marikina Heights, Barangay Concepcion',
                'province' => 'Metro Manila',
                'city' => 'Marikina',
                'barangay' => 'Concepcion',
                'street' => 'Marikina Heights',
                'type' => 'outpatient',
                'bed_id' => null,
                'blood_type' => 'AB-',
                'emergency_contact_person' => 'Rosa Aquino',
                'emergency_contact_relationship' => 'Mother',
                'emergency_contact_phone' => '09259012346',
                'insurance_provider' => 'Medicard',
                'insurance_number' => 'MED-741852963',
                'vitals_bp' => '105/65',
                'vitals_hr' => 62,
                'vitals_temp' => 36.6,
                'medical_history' => 'Allergy consultation, seasonal allergies',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'PAT-241204-0010',
                'first_name' => 'Daniel',
                'middle_name' => 'Castillo',
                'last_name' => 'Rivera',
                'email' => 'daniel.rivera@email.com',
                'phone' => '09260123456',
                'date_of_birth' => '1987-08-14',
                'gender' => 'male',
                'civil_status' => 'married',
                'place_of_birth' => 'Valenzuela',
                'address' => '741 MacArthur Highway, Barangay Karuhatan',
                'province' => 'Metro Manila',
                'city' => 'Valenzuela',
                'barangay' => 'Karuhatan',
                'street' => 'MacArthur Highway',
                'type' => 'outpatient',
                'bed_id' => null,
                'blood_type' => 'A+',
                'emergency_contact_person' => 'Maria Rivera',
                'emergency_contact_relationship' => 'Wife',
                'emergency_contact_phone' => '09260123457',
                'insurance_provider' => 'Maxicare',
                'insurance_number' => 'MAX-852963741',
                'vitals_bp' => '128/82',
                'vitals_hr' => 77,
                'vitals_temp' => 37.3,
                'medical_history' => 'Physical therapy follow-up, knee injury',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'PAT-241204-0011',
                'first_name' => 'Patricia',
                'middle_name' => 'Morales',
                'last_name' => 'Gonzales',
                'email' => 'patricia.gonzales@email.com',
                'phone' => '09271234567',
                'date_of_birth' => '1996-10-07',
                'gender' => 'female',
                'civil_status' => 'single',
                'place_of_birth' => 'Las Piñas',
                'address' => '852 Alabang-Zapote Road, Barangay Almanza',
                'province' => 'Metro Manila',
                'city' => 'Las Piñas',
                'barangay' => 'Almanza',
                'street' => 'Alabang-Zapote Road',
                'type' => 'outpatient',
                'bed_id' => null,
                'blood_type' => 'B+',
                'emergency_contact_person' => 'Robert Gonzales',
                'emergency_contact_relationship' => 'Brother',
                'emergency_contact_phone' => '09271234568',
                'insurance_provider' => 'Cigna',
                'insurance_number' => 'CIG-963741852',
                'vitals_bp' => '112/72',
                'vitals_hr' => 66,
                'vitals_temp' => 36.8,
                'medical_history' => 'Dermatology consultation, acne treatment',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'PAT-241204-0012',
                'first_name' => 'Mark',
                'middle_name' => 'Sanchez',
                'last_name' => 'Diaz',
                'email' => 'mark.diaz@email.com',
                'phone' => '09282345678',
                'date_of_birth' => '1991-02-28',
                'gender' => 'male',
                'civil_status' => 'single',
                'place_of_birth' => 'Muntinlupa',
                'address' => '963 National Road, Barangay Poblacion',
                'province' => 'Metro Manila',
                'city' => 'Muntinlupa',
                'barangay' => 'Poblacion',
                'street' => 'National Road',
                'type' => 'outpatient',
                'bed_id' => null,
                'blood_type' => 'O+',
                'emergency_contact_person' => 'Lisa Diaz',
                'emergency_contact_relationship' => 'Sister',
                'emergency_contact_phone' => '09282345679',
                'insurance_provider' => 'PhilHealth',
                'insurance_number' => 'PH-147258369',
                'vitals_bp' => '122/78',
                'vitals_hr' => 73,
                'vitals_temp' => 37.0,
                'medical_history' => 'General consultation, flu symptoms',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        $ids = array_column($patients, 'id');
        if (!empty($ids)) {
            $this->db->table('patients')->whereIn('id', $ids)->delete();
        }

        $this->db->table('patients')->insertBatch($patients);
    }
}

