<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class PhilHealthCaseRatesSeeder extends Seeder
{
    public function run()
    {
        $timestamp = date('Y-m-d H:i:s');

        $data = [
            // RVS-based (Case B preferred). Appendectomy
            [
                'code_type' => 'RVS',
                'code' => '48010',
                'description' => 'Appendectomy',
                'case_type' => 'B',
                'rate_total' => 21000.00,
                'facility_share' => 14700.00,
                'professional_share' => 6300.00,
                'effective_from' => '2024-01-01',
                'effective_to' => null,
                'active' => 1,
                'updated_by' => 'seeder',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // RVS alternative effective window (older rate to test date selection)
            [
                'code_type' => 'RVS',
                'code' => '48010',
                'description' => 'Appendectomy (old rate)',
                'case_type' => 'B',
                'rate_total' => 20000.00,
                'facility_share' => 14000.00,
                'professional_share' => 6000.00,
                'effective_from' => '2023-01-01',
                'effective_to' => '2023-12-31',
                'active' => 1,
                'updated_by' => 'seeder',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // ICD-based (Case A). Pneumonia, unspecified organism
            [
                'code_type' => 'ICD',
                'code' => 'J18.9',
                'description' => 'Pneumonia, unspecified organism',
                'case_type' => 'A',
                'rate_total' => 15000.00,
                'facility_share' => 10500.00,
                'professional_share' => 4500.00,
                'effective_from' => '2024-01-01',
                'effective_to' => null,
                'active' => 1,
                'updated_by' => 'seeder',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // ICD-based (Case A). Dengue fever
            [
                'code_type' => 'ICD',
                'code' => 'A90',
                'description' => 'Dengue fever (classical dengue)',
                'case_type' => 'A',
                'rate_total' => 10000.00,
                'facility_share' => 7000.00,
                'professional_share' => 3000.00,
                'effective_from' => '2024-01-01',
                'effective_to' => null,
                'active' => 1,
                'updated_by' => 'seeder',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // Another RVS - Cholecystectomy (example values)
            [
                'code_type' => 'RVS',
                'code' => '47562',
                'description' => 'Laparoscopic cholecystectomy',
                'case_type' => 'B',
                'rate_total' => 31000.00,
                'facility_share' => 21700.00,
                'professional_share' => 9300.00,
                'effective_from' => '2024-01-01',
                'effective_to' => null,
                'active' => 1,
                'updated_by' => 'seeder',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // An ICD with older effectivity to test boundary
            [
                'code_type' => 'ICD',
                'code' => 'I10',
                'description' => 'Essential (primary) hypertension',
                'case_type' => 'A',
                'rate_total' => 6000.00,
                'effective_from' => '2022-01-01',
                'effective_to' => '2023-12-31',
                'active' => 1,
                'updated_by' => 'seeder',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            
            // ========== LABORATORY TESTS (Matching services: LAB-BLOOD, LAB-URINE, IMG-XRAY, IMG-MRI, IMG-CT, IMG-US, CARD-ECG) ==========
            // Blood Test - matches LAB-BLOOD
            [
                'code_type' => 'RVS',
                'code' => 'LAB-BLOOD',
                'description' => 'Blood Test (CBC)',
                'case_type' => 'A',
                'rate_total' => 500.00,
                'facility_share' => 300.00,
                'professional_share' => 200.00,
                'effective_from' => '2024-01-01',
                'effective_to' => null,
                'active' => 1,
                'updated_by' => 'seeder',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // Urine Test - matches LAB-URINE
            [
                'code_type' => 'RVS',
                'code' => 'LAB-URINE',
                'description' => 'Urine Test (Urinalysis)',
                'case_type' => 'A',
                'rate_total' => 375.00,
                'facility_share' => 225.00,
                'professional_share' => 150.00,
                'effective_from' => '2024-01-01',
                'effective_to' => null,
                'active' => 1,
                'updated_by' => 'seeder',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // X-Ray - matches IMG-XRAY
            [
                'code_type' => 'RVS',
                'code' => 'IMG-XRAY',
                'description' => 'X-Ray (Chest)',
                'case_type' => 'B',
                'rate_total' => 1000.00,
                'facility_share' => 800.00,
                'professional_share' => 200.00,
                'effective_from' => '2024-01-01',
                'effective_to' => null,
                'active' => 1,
                'updated_by' => 'seeder',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // MRI Scan - matches IMG-MRI
            [
                'code_type' => 'RVS',
                'code' => 'IMG-MRI',
                'description' => 'MRI Scan (Brain)',
                'case_type' => 'C',
                'rate_total' => 10000.00,
                'facility_share' => 8000.00,
                'professional_share' => 2000.00,
                'effective_from' => '2024-01-01',
                'effective_to' => null,
                'active' => 1,
                'updated_by' => 'seeder',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // CT Scan - matches IMG-CT
            [
                'code_type' => 'RVS',
                'code' => 'IMG-CT',
                'description' => 'CT Scan (Head)',
                'case_type' => 'C',
                'rate_total' => 5000.00,
                'facility_share' => 4000.00,
                'professional_share' => 1000.00,
                'effective_from' => '2024-01-01',
                'effective_to' => null,
                'active' => 1,
                'updated_by' => 'seeder',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // Ultrasound - matches IMG-US
            [
                'code_type' => 'RVS',
                'code' => 'IMG-US',
                'description' => 'Ultrasound (Whole Abdomen)',
                'case_type' => 'B',
                'rate_total' => 3000.00,
                'facility_share' => 2000.00,
                'professional_share' => 1000.00,
                'effective_from' => '2024-01-01',
                'effective_to' => null,
                'active' => 1,
                'updated_by' => 'seeder',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // ECG - matches CARD-ECG
            [
                'code_type' => 'RVS',
                'code' => 'CARD-ECG',
                'description' => 'Electrocardiogram (ECG)',
                'case_type' => 'A',
                'rate_total' => 750.00,
                'facility_share' => 450.00,
                'professional_share' => 300.00,
                'effective_from' => '2024-01-01',
                'effective_to' => null,
                'active' => 1,
                'updated_by' => 'seeder',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            
            // ========== ROOM & BED CHARGES (Matching services: ROOM-ICU, ROOM-NICU, ROOM-PRIVATE, ROOM-SEMIPRIVATE, ROOM-WARD, ROOM-PEDIA, ROOM-ISOLATION, ROOM-SDU, ROOM-ED, ROOM-LD) ==========
            // ICU Room - matches ROOM-ICU
            [
                'code_type' => 'RVS',
                'code' => 'ROOM-ICU',
                'description' => 'Intensive Care Unit (ICU)',
                'case_type' => 'B',
                'rate_total' => 1500.00,
                'facility_share' => 1500.00,
                'professional_share' => 0.00,
                'effective_from' => '2024-01-01',
                'effective_to' => null,
                'active' => 1,
                'updated_by' => 'seeder',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // NICU Room - matches ROOM-NICU
            [
                'code_type' => 'RVS',
                'code' => 'ROOM-NICU',
                'description' => 'Neonatal Intensive Care Unit (NICU)',
                'case_type' => 'B',
                'rate_total' => 1500.00,
                'facility_share' => 1500.00,
                'professional_share' => 0.00,
                'effective_from' => '2024-01-01',
                'effective_to' => null,
                'active' => 1,
                'updated_by' => 'seeder',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // Private Room - matches ROOM-PRIVATE
            [
                'code_type' => 'RVS',
                'code' => 'ROOM-PRIVATE',
                'description' => 'Private Room Accommodation',
                'case_type' => 'A',
                'rate_total' => 1100.00,
                'facility_share' => 1100.00,
                'professional_share' => 0.00,
                'effective_from' => '2024-01-01',
                'effective_to' => null,
                'active' => 1,
                'updated_by' => 'seeder',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // Semi-Private Room - matches ROOM-SEMIPRIVATE
            [
                'code_type' => 'RVS',
                'code' => 'ROOM-SEMIPRIVATE',
                'description' => 'Semi-Private Room Accommodation',
                'case_type' => 'A',
                'rate_total' => 800.00,
                'facility_share' => 800.00,
                'professional_share' => 0.00,
                'effective_from' => '2024-01-01',
                'effective_to' => null,
                'active' => 1,
                'updated_by' => 'seeder',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // General Ward - matches ROOM-WARD
            [
                'code_type' => 'RVS',
                'code' => 'ROOM-WARD',
                'description' => 'General Ward Accommodation',
                'case_type' => 'A',
                'rate_total' => 500.00,
                'facility_share' => 500.00,
                'professional_share' => 0.00,
                'effective_from' => '2024-01-01',
                'effective_to' => null,
                'active' => 1,
                'updated_by' => 'seeder',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // Pediatric Ward - matches ROOM-PEDIA
            [
                'code_type' => 'RVS',
                'code' => 'ROOM-PEDIA',
                'description' => 'Pediatric Ward Accommodation',
                'case_type' => 'A',
                'rate_total' => 500.00,
                'facility_share' => 500.00,
                'professional_share' => 0.00,
                'effective_from' => '2024-01-01',
                'effective_to' => null,
                'active' => 1,
                'updated_by' => 'seeder',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // Isolation Room - matches ROOM-ISOLATION
            [
                'code_type' => 'RVS',
                'code' => 'ROOM-ISOLATION',
                'description' => 'Isolation Room',
                'case_type' => 'A',
                'rate_total' => 1000.00,
                'facility_share' => 1000.00,
                'professional_share' => 0.00,
                'effective_from' => '2024-01-01',
                'effective_to' => null,
                'active' => 1,
                'updated_by' => 'seeder',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // Step-Down Unit - matches ROOM-SDU
            [
                'code_type' => 'RVS',
                'code' => 'ROOM-SDU',
                'description' => 'Step-Down Unit',
                'case_type' => 'A',
                'rate_total' => 800.00,
                'facility_share' => 800.00,
                'professional_share' => 0.00,
                'effective_from' => '2024-01-01',
                'effective_to' => null,
                'active' => 1,
                'updated_by' => 'seeder',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // Emergency Department - matches ROOM-ED
            [
                'code_type' => 'RVS',
                'code' => 'ROOM-ED',
                'description' => 'Emergency Department',
                'case_type' => 'A',
                'rate_total' => 500.00,
                'facility_share' => 500.00,
                'professional_share' => 0.00,
                'effective_from' => '2024-01-01',
                'effective_to' => null,
                'active' => 1,
                'updated_by' => 'seeder',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // Labor & Delivery - matches ROOM-LD
            [
                'code_type' => 'RVS',
                'code' => 'ROOM-LD',
                'description' => 'Labor & Delivery Room',
                'case_type' => 'A',
                'rate_total' => 500.00,
                'facility_share' => 500.00,
                'professional_share' => 0.00,
                'effective_from' => '2024-01-01',
                'effective_to' => null,
                'active' => 1,
                'updated_by' => 'seeder',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            
            // ========== CONSULTATION & PROFESSIONAL FEES (Matching services: CONS-CONSULT, CONS-FOLLOWUP, CONS-EMERGENCY, CONS-ROUTINE) ==========
            // Consultation Fee - matches CONS-CONSULT
            [
                'code_type' => 'RVS',
                'code' => 'CONS-CONSULT',
                'description' => 'Consultation Fee',
                'case_type' => 'A',
                'rate_total' => 500.00,
                'facility_share' => 0.00,
                'professional_share' => 500.00,
                'effective_from' => '2024-01-01',
                'effective_to' => null,
                'active' => 1,
                'updated_by' => 'seeder',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // Follow-up Consultation - matches CONS-FOLLOWUP
            [
                'code_type' => 'RVS',
                'code' => 'CONS-FOLLOWUP',
                'description' => 'Follow-up Consultation',
                'case_type' => 'A',
                'rate_total' => 300.00,
                'facility_share' => 0.00,
                'professional_share' => 300.00,
                'effective_from' => '2024-01-01',
                'effective_to' => null,
                'active' => 1,
                'updated_by' => 'seeder',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // Emergency Consultation - matches CONS-EMERGENCY
            [
                'code_type' => 'RVS',
                'code' => 'CONS-EMERGENCY',
                'description' => 'Emergency Consultation',
                'case_type' => 'B',
                'rate_total' => 1000.00,
                'facility_share' => 500.00,
                'professional_share' => 500.00,
                'effective_from' => '2024-01-01',
                'effective_to' => null,
                'active' => 1,
                'updated_by' => 'seeder',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // Routine Checkup - matches CONS-ROUTINE
            [
                'code_type' => 'RVS',
                'code' => 'CONS-ROUTINE',
                'description' => 'Routine Checkup',
                'case_type' => 'A',
                'rate_total' => 400.00,
                'facility_share' => 0.00,
                'professional_share' => 400.00,
                'effective_from' => '2024-01-01',
                'effective_to' => null,
                'active' => 1,
                'updated_by' => 'seeder',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            
            // ========== PROFESSIONAL FEES (Matching service: FEE-DOCTOR-DAILY) ==========
            // Daily Professional Fee - matches FEE-DOCTOR-DAILY
            [
                'code_type' => 'RVS',
                'code' => 'FEE-DOCTOR-DAILY',
                'description' => 'Professional Fee (Daily)',
                'case_type' => 'A',
                'rate_total' => 500.00,
                'facility_share' => 0.00,
                'professional_share' => 500.00,
                'effective_from' => '2024-01-01',
                'effective_to' => null,
                'active' => 1,
                'updated_by' => 'seeder',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        $normalizedData = array_map(function (array $row) use ($timestamp) {
            $row['id'] = $row['id'] ?? null; // satisfy implicit column list
            $row['facility_share'] = $row['facility_share'] ?? 0;
            $row['professional_share'] = $row['professional_share'] ?? 0;
            $row['description'] = $row['description'] ?? null;
            $row['active'] = $row['active'] ?? 1;
            $row['updated_by'] = $row['updated_by'] ?? 'seeder';
            $row['created_at'] = $row['created_at'] ?? $timestamp;
            $row['updated_at'] = $row['updated_at'] ?? $timestamp;
            return $row;
        }, $data);

        $this->db->table('philhealth_case_rates')->insertBatch($normalizedData);
    }
}
