<?php $this->extend('partials/header') ?>

<?= $this->section('title') ?>Add Test Result<?= $this->endSection() ?>

<?= $this->section('content') ?>
    <div class="main-content" id="mainContent">
        <div class="page-header">
            <h1 class="page-title">Add Test Result</h1>
        </div>

        <div class="card">
            <div class="card-header">
                Test Information
            </div>
            <div class="card-body">
                <form method="post" action="<?= site_url('laboratory/testresult/add') ?>" id="addResultForm" enctype="multipart/form-data">
                    <?= csrf_field() ?>
                    <input type="hidden" name="test_id" value="<?= esc($testResult['id']) ?>">
                    <div class="form-grid">
                        <div class="form-group">
                            <label class="form-label">Patient Name</label>
                            <input type="text" class="form-control" value="<?= htmlspecialchars($testResult['test_name']) ?>" readonly>
                        </div>
                        <div class="form-group">
                            <label class="form-label">Test Type</label>
                            <input type="text" class="form-control" value="<?= htmlspecialchars($testResult['test_type']) ?>" readonly>
                        </div>
                        <div class="form-group">
                            <label class="form-label">Test Date</label>
                            <input type="text" class="form-control" value="<?= date('F j, Y', strtotime($testResult['test_date'])) ?>" readonly>
                        </div>
                        <div class="form-group">
                            <label class="form-label">Current Status</label>
                            <input type="text" class="form-control" value="<?= ucfirst($testResult['status']) ?>" readonly>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="form-label" for="resultFile">Analyzer Output File</label>
                        <input type="file" class="form-control" id="resultFile" name="result_file" accept=".pdf,.csv,.txt,.xml,.json,.xls,.xlsx,.doc,.docx,.jpg,.jpeg,.png">
                        <small class="form-text text-muted">Upload the file generated by the lab equipment (PDF, CSV, Excel, image, etc.). This file is required.</small>
                    </div>

                    <div class="form-group">
                        <label for="interpretation" class="form-label">Clinical Interpretation (optional)</label>
                        <textarea class="form-control" id="interpretation" name="interpretation" rows="3" placeholder="Enter clinical interpretation of results..."></textarea>
                    </div>

                    <div class="form-group">
                        <label for="notes" class="form-label">Additional Notes</label>
                        <textarea class="form-control" id="notes" name="notes" rows="3" placeholder="Enter any additional notes..."></textarea>
                    </div>

                    <div class="form-actions" style="display: flex; gap: 1rem; justify-content: flex-end;">
                        <a href="<?= base_url('laboratory/testresult') ?>" class="btn btn-secondary">
                            <i class="fas fa-arrow-left"></i>Back to Results
                        </a>
                        <button type="submit" class="btn btn-primary">
                            <i class="fas fa-save"></i>Save Result & Mark Completed
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script>
        // Form submission handling
        document.getElementById('addResultForm').addEventListener('submit', function(e) {
            const fileInput = document.getElementById('resultFile');
            const submitButton = this.querySelector('button[type="submit"]');

            if (!fileInput || fileInput.files.length === 0) {
                e.preventDefault();
                alert('Please upload the analyzer output file before saving.');
                return false;
            }

            if (submitButton) {
                submitButton.disabled = true;
                submitButton.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Saving...';
            }
        });

        // Sidebar toggle functionality
        document.addEventListener('DOMContentLoaded', function() {
            const sidebar = document.querySelector('.sidebar');
            const mainContent = document.getElementById('mainContent');
            
            if (sidebar && mainContent) {
                const toggleSidebar = () => {
                    if (sidebar.classList.contains('closed')) {
                        mainContent.classList.add('expanded');
                    } else {
                        mainContent.classList.remove('expanded');
                    }
                };

                // Initial check
                toggleSidebar();

                // Add event listener for sidebar toggle
                const toggleBtn = document.querySelector('.toggle-btn');
                if (toggleBtn) {
                    toggleBtn.addEventListener('click', toggleSidebar);
                }
            }
        });
    </script>
<?= $this->endSection() ?>
